import * as THREE from "https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js";
const C={r:3.35,h:2.65,len:3.75,rad:.075,climb:.42};
const $=s=>document.querySelector(s),game=$("#game"),startScreen=$("#start-screen"),deathScreen=$("#death-screen"),msg=$("#message");
let scene,camera,renderer,raycaster,barsGroup,barData=new Map(),layers=new Map(),player={layer:0,x:0,y:1,z:0},running=false,dead=false,hard=false,climbing=false,climb={start:0,from:{},to:{},id:null},yaw=0,pitch=-.12,pointer=null,moved=false,last=performance.now();
const normalMat=new THREE.MeshStandardMaterial({color:0x777777,roughness:.9}),wallMat=new THREE.MeshStandardMaterial({color:0x272727,side:THREE.DoubleSide,roughness:1}),looseMat=new THREE.MeshStandardMaterial({color:0x8f5b3d,roughness:1});
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}function smooth(t){return t*t*(3-2*t)}
function init(){scene=new THREE.Scene();scene.background=new THREE.Color(0x020202);scene.fog=new THREE.FogExp2(0x020202,.075);camera=new THREE.PerspectiveCamera(67,innerWidth/innerHeight,.03,180);renderer=new THREE.WebGLRenderer({antialias:false});renderer.setPixelRatio(1);resize();renderer.domElement.style.width="100%";renderer.domElement.style.height="100%";game.appendChild(renderer.domElement);scene.add(new THREE.AmbientLight(0x777777,.5));let light=new THREE.PointLight(0x9ba8b8,2.4,12);light.position.set(0,1,0);scene.add(light);let wall=new THREE.Mesh(new THREE.CylinderGeometry(C.r,C.r,220,16,1,true),wallMat);wall.position.y=105;scene.add(wall);let floor=new THREE.Mesh(new THREE.CylinderGeometry(C.r-.05,C.r-.05,.25,16),wallMat);floor.position.y=-1.5;scene.add(floor);barsGroup=new THREE.Group();scene.add(barsGroup);raycaster=new THREE.Raycaster();reset();renderer.domElement.addEventListener("pointerdown",down);renderer.domElement.addEventListener("pointermove",move);renderer.domElement.addEventListener("pointerup",up);renderer.domElement.addEventListener("pointercancel",()=>pointer=null);$("#start-button").addEventListener("click",()=>start(false));$("#hard-button").addEventListener("click",()=>start(true));$("#restart-button").addEventListener("click",()=>start(hard));addEventListener("resize",resize);requestAnimationFrame(loop)}
function reset(){barData.clear();layers.clear();while(barsGroup.children.length)barsGroup.remove(barsGroup.children[0]);for(let l=0;l<100;l++)makeLayer(l);player={layer:0,x:0,y:1,z:0};camera.position.set(0,1,0);yaw=0;pitch=-.12;camera.rotation.order="YXZ";camera.rotation.set(pitch,yaw,0);climbing=false;show("ONE IN THE WELL.",1600)}
function makeLayer(l){let arr=[],n=l===0?3:1+Math.floor(Math.random()*3),used=[];for(let i=0;i<n;i++){let a=Math.random()*Math.PI*2;for(let k=0;k<30&&used.some(v=>Math.abs(Math.atan2(Math.sin(a-v),Math.cos(a-v)))<.6);k++)a=Math.random()*Math.PI*2;used.push(a);let id=`${l}:${i}`,g=new THREE.Group();g.position.set(Math.cos(a)*(C.r-.18),l*C.h,Math.sin(a)*(C.r-.18));g.rotation.y=a;let loose=l>20&&Math.random()<Math.min(.33,.1+l/450),m=new THREE.Mesh(new THREE.CylinderGeometry(C.rad,C.rad,C.len,6),loose?looseMat:normalMat);m.rotation.z=Math.PI/2;m.userData.id=id;g.add(m);let hit=new THREE.Mesh(new THREE.BoxGeometry(C.len+1,.85,1),new THREE.MeshBasicMaterial({transparent:true,opacity:0,depthWrite:false}));hit.userData.id=id;g.add(hit);barsGroup.add(g);let b={id,layer:l,group:g,loose,held:0};barData.set(id,b);arr.push(b)}layers.set(l,arr)}
function start(h){hard=h;startScreen.classList.add("hidden");deathScreen.classList.add("hidden");running=true;dead=false;reset()}
function show(t,ms){msg.textContent=t;msg.classList.add("show");clearTimeout(show.timer);show.timer=setTimeout(()=>msg.classList.remove("show"),ms)}
function down(e){if(!running||dead)return;pointer={id:e.pointerId,x:e.clientX,y:e.clientY};moved=false;try{renderer.domElement.setPointerCapture(e.pointerId)}catch{}}
function move(e){if(!pointer||e.pointerId!==pointer.id)return;let dx=e.clientX-pointer.x,dy=e.clientY-pointer.y;if(Math.abs(dx)+Math.abs(dy)>4)moved=true;yaw-=dx*.006;pitch=clamp(pitch-dy*.005,-1.4,1.4);pointer.x=e.clientX;pointer.y=e.clientY;camera.rotation.order="YXZ";camera.rotation.y=yaw;camera.rotation.x=pitch}
function up(e){if(!pointer||e.pointerId!==pointer.id)return;if(!moved)tap(e.clientX,e.clientY);pointer=null}
function tap(x,y){if(climbing)return;let r=renderer.domElement.getBoundingClientRect(),v=new THREE.Vector2((x-r.left)/r.width*2-1,-(y-r.top)/r.height*2+1);raycaster.setFromCamera(v,camera);let hits=raycaster.intersectObjects(barsGroup.children,true);if(!hits.length)return;let b=barData.get(hits[0].object.userData.id);if(!b||b.layer!==player.layer+1)return;climbing=true;climb={start:performance.now(),from:{x:camera.position.x,y:camera.position.y,z:camera.position.z},to:{x:b.group.position.x,y:b.group.position.y+1,z:b.group.position.z},id:b.id};b.held=performance.now()}
function loop(now){let dt=Math.min(.05,(now-last)/1000);last=now;if(running&&!dead){if(climbing){let t=clamp((now-climb.start)/(C.climb*1000),0,1),q=smooth(t);camera.position.set(THREE.MathUtils.lerp(climb.from.x,climb.to.x,q),THREE.MathUtils.lerp(climb.from.y,climb.to.y,q),THREE.MathUtils.lerp(climb.from.z,climb.to.z,q));if(t>=1){let b=barData.get(climb.id);if(b){player={layer:b.layer,x:b.group.position.x,y:b.group.position.y+1,z:b.group.position.z};camera.position.set(player.x,player.y,player.z)}climbing=false;if(player.layer===45)show("TWO IN THE WELL.",2200)}}else camera.position.set(player.x,player.y,player.z)}renderer.render(scene,camera);requestAnimationFrame(loop)}
function resize(){if(!camera||!renderer)return;camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(Math.max(320,Math.floor(innerWidth/1.55)),Math.max(240,Math.floor(innerHeight/1.55)),false)}
init();