import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
const $=id=>document.getElementById(id);const canvas=$('game');let renderer,scene,camera,clock,mode='steals',running=false,maze=[],N=17,cell=3,player,monster,orbs=[],walls=[],furniture=[],keys={},yaw=0,pitch=0,move={x:0,y:0},isRunning=false,orbTotal=25,batteries=10,aggression=0,threshold=3,state='stalk',stateTime=0,toastTimer=0,flashTimer=0,stun=0,monsterTarget=null,monsterPath=[],pathTimer=0,shake=0,moveSpeed=2.1,monsterSpeed=4.2,basePos={x:0,z:0};
function initRenderer(){renderer=new THREE.WebGLRenderer({canvas,antialias:false,alpha:false});renderer.setPixelRatio(1);renderer.setSize(Math.max(240,Math.floor(innerWidth/2)),Math.max(160,Math.floor(innerHeight/2)),false);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.NoToneMapping;scene=new THREE.Scene();scene.background=new THREE.Color(0x000000);scene.fog=new THREE.FogExp2(0x000000,.095);camera=new THREE.PerspectiveCamera(72,innerWidth/innerHeight,.08,90);clock=new THREE.Clock();}
initRenderer();window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(Math.max(240,Math.floor(innerWidth/2)),Math.max(160,Math.floor(innerHeight/2)),false)});
const mat=(color,roughness=1)=>new THREE.MeshStandardMaterial({color,roughness});const white=mat(0xbdbdbd),black=mat(0x171717),dark=mat(0x080808),blue=new THREE.MeshBasicMaterial({color:0x16aaff}),red=new THREE.MeshBasicMaterial({color:0xff1010});
function box(w,h,d,m,x,y,z){const o=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),m);o.position.set(x,y,z);scene.add(o);return o}
function generateMaze(){maze=Array.from({length:N},()=>Array.from({length:N},()=>({v:1,seen:false})));let stack=[[1,1]];maze[1][1].v=0;while(stack.length){let [x,z]=stack[stack.length-1],opts=[];for(const [dx,dz] of [[2,0],[-2,0],[0,2],[0,-2]]){let nx=x+dx,nz=z+dz;if(nx>0&&nz>0&&nx<N-1&&nz<N-1&&maze[nz][nx].v){opts.push([nx,nz,dx,dz])}}if(!opts.length){stack.pop();continue}let [nx,nz,dx,dz]=opts[Math.floor(Math.random()*opts.length)];maze[z+dz/2][x+dx/2].v=0;maze[nz][nx].v=0;stack.push([nx,nz])} // open a few loops
for(let z=1;z<N-1;z++)for(let x=1;x<N-1;x++)if(maze[z][x].v&&Math.random()<.08&&((maze[z-1][x].v===0&&maze[z+1][x].v===0)||(maze[z][x-1].v===0&&maze[z][x+1].v===0)))maze[z][x].v=0;
// room pockets
for(let z=2;z<N-2;z+=4)for(let x=2;x<N-2;x+=4)if(Math.random()<.55){for(let dz=0;dz<2;dz++)for(let dx=0;dx<2;dx++)maze[z+dz][x+dx].v=0}
}
function clearScene(){for(const o of [...walls,...furniture,...orbs])scene.remove(o);walls=[];furniture=[];orbs=[];if(monster)scene.remove(monster)}
function buildWorld(){clearScene();generateMaze();const floorMat=new THREE.MeshStandardMaterial({color:0xffffff,roughness:1});for(let z=0;z<N;z++)for(let x=0;x<N;x++){let wx=(x-N/2)*cell,wz=(z-N/2)*cell;if(maze[z][x].v){let o=box(cell,3.6,cell,black,wx,1.8,wz);walls.push(o)}else{let o=box(cell,.12,cell,((x+z)%2?white:black),wx,-.08,wz);walls.push(o);if(Math.random()<.055&&!(x===1&&z===1)){let f=box(.9,.8,.8,mat(0x282828),wx,.4,wz);furniture.push(f);if(Math.random()<.5)box(.12,1.2,.12,mat(0x383838),wx+.25,1,wz+.2)}}}
player.position.set((1-N/2)*cell,1.55,(1-N/2)*cell);basePos={x:player.position.x,z:player.position.z};let floors=[];for(let z=1;z<N-1;z++)for(let x=1;x<N-1;x++)if(!maze[z][x].v&&!(x===1&&z===1))floors.push([x,z]);shuffle(floors);for(let i=0;i<25;i++){let [x,z]=floors[i%floors.length],o=new THREE.Mesh(new THREE.IcosahedronGeometry(.28,1),blue);o.position.set((x-N/2)*cell,.85,(z-N/2)*cell);scene.add(o);orbs.push(o)}
let far=floors.reduce((best,p)=>distGrid(p,[1,1])>distGrid(best,[1,1])?p:best,floors[0]);monster.position.set((far[0]-N/2)*cell,0,(far[1]-N/2)*cell);monster.rotation.y=Math.random()*Math.PI*2;state='stalk';stateTime=0;aggression=0;threshold=2+Math.floor(Math.random()*4);batteries=10;orbTotal=25;}
function shuffle(a){for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}}
function distGrid(a,b){return Math.abs(a[0]-b[0])+Math.abs(a[1]-b[1])}
function makeMonster(){monster=new THREE.Group();const body=mat(0x080808);let head=new THREE.Mesh(new THREE.BoxGeometry(.85,.8,.8),body);head.position.y=2.55;monster.add(head);for(let s of [-1,1]){let leg=new THREE.Mesh(new THREE.BoxGeometry(.48,1.9,.5),body);leg.position.set(s*.38,.95,0);monster.add(leg);let eye=new THREE.Mesh(new THREE.SphereGeometry(.13,6,5),red);eye.position.set(s*.22,2.62,-.414);monster.add(eye)}let glow=new THREE.PointLight(0xff1010,0,11,2);glow.position.set(0,2.5,-.3);monster.add(glow);monster.userData.glow=glow;scene.add(monster)}
player=new THREE.Object3D();player.position.set(0,1.55,0);makeMonster();const ambient=new THREE.AmbientLight(0xffffff,.012);scene.add(ambient);const flashlight=new THREE.SpotLight(0xffffff,mode==='steals'?7:0,18,Math.PI/7,.65,1.5);flashlight.position.set(0,0,0);camera.add(flashlight);camera.add(flashlight.target);scene.add(camera);camera.add(new THREE.PointLight(0xffffff,.14,4));
function start(m){mode=m;running=true;$('menu').hidden=true;$('hud').hidden=false;$('ending').hidden=true;buildWorld();$('battery').style.display=mode==='shutter'?'':'none';$('action').textContent=mode==='shutter'?'SNAP':'FLASH';$('runWarning').style.display='none';clock.getDelta();}
function gridAt(x,z){return [Math.floor(x/cell+N/2),Math.floor(z/cell+N/2)]}
function walkable(x,z){let [gx,gz]=gridAt(x,z);return gx>=0&&gz>=0&&gx<N&&gz<N&&!maze[gz][gx].v}
function moveEntity(obj,dx,dz){let nx=obj.position.x+dx,nz=obj.position.z+dz;if(walkable(nx+.28*Math.sign(dx),obj.position.z)&&walkable(nx,obj.position.z+.25*Math.sign(dz)))obj.position.x=nx;if(walkable(obj.position.x,obj.position.z+dz))obj.position.z+=dz}
function bfs(start,goal){let q=[start],prev=new Map([[start.join(','),null]]);for(let i=0;i<q.length;i++){let p=q[i];if(p[0]===goal[0]&&p[1]===goal[1])break;for(let [dx,dz] of [[1,0],[-1,0],[0,1],[0,-1]]){let n=[p[0]+dx,p[1]+dz],k=n.join(',');if(n[0]>=0&&n[1]>=0&&n[0]<N&&n[1]<N&&!maze[n[1]][n[0]].v&&!prev.has(k)){prev.set(k,p);q.push(n)}}}let k=goal.join(',');if(!prev.has(k))return [];let out=[];while(k){let p=k.split(',').map(Number);out.unshift(p);let v=prev.get(k);k=v?v.join(','):null}return out}
function nearestOpen(p){let [x,z]=gridAt(p.x,p.z);if(walkable(p.x,p.z))return [x,z];for(let r=1;r<N;r++)for(let dz=-r;dz<=r;dz++)for(let dx=-r;dx<=r;dx++){let a=x+dx,b=z+dz;if(a>=0&&b>=0&&a<N&&b<N&&!maze[b][a].v)return[a,b]}return[1,1]}
function flash(){if(!running)return;if(mode==='shutter'&&batteries<=0)return;if(mode==='shutter')batteries--;flashTimer=.22;if(state==='chase'){if(mode==='shutter'){stun=5;toast('STUNNED');return}else return}if(state==='stalk'){aggression++;state='retreat';stateTime=0;toast('');const p=nearestOpen(player.position);let far=[1,1],best=-1;for(let z=1;z<N-1;z++)for(let x=1;x<N-1;x++)if(!maze[z][x].v){let d=distGrid([x,z],p);if(d>best){best=d;far=[x,z]}}monsterPath=bfs(nearestOpen(monster.position),far);pathTimer=0;if(aggression>=threshold){state='trigger';stateTime=0;$('runWarning').style.display='block'}}}
function toast(t){$('toast').textContent=t;toastTimer=1}
function updateMonster(dt){stateTime+=dt;if(stun>0){stun-=dt;return}if(state==='trigger'){if(stateTime>=3){state='chase';stateTime=0;$('runWarning').style.display='none';toast('');}return}if(state==='chase'&&stateTime>=(15+Math.random()*15)){state='retreat';stateTime=0;monsterPath=[]}
if(state==='stalk'||state==='chase'){pathTimer-=dt;if(pathTimer<=0){pathTimer=.7;let p=nearestOpen(player.position),m=nearestOpen(monster.position),goal=p;if(state==='stalk'){let candidates=[];for(let z=1;z<N-1;z++)for(let x=1;x<N-1;x++)if(!maze[z][x].v)candidates.push([x,z]);goal=candidates.reduce((b,a)=>distGrid(a,p)>distGrid(b,p)?a:b,candidates[0]);}monsterPath=bfs(m,goal)}const speed=state==='chase'?monsterSpeed*(isRunning?1.25:1):monsterSpeed*(isRunning?1.2:1);followPath(dt,speed);if(state==='chase'){monster.userData.glow.intensity=2.8;monster.userData.glow.distance=13}else monster.userData.glow.intensity=0;if(monster.position.distanceTo(player.position)<.9){if(state==='chase'){toast('CAUGHT');state='reset';stateTime=0}}}else if(state==='retreat'){followPath(dt,monsterSpeed*1.5);if(!monsterPath.length||stateTime>12){state='stalk';stateTime=0}}else if(state==='reset'){if(stateTime>1.5){buildWorld();toast('')}}}
function followPath(dt,speed){if(!monsterPath.length)return;let [x,z]=monsterPath[0],tx=(x-N/2)*cell,tz=(z-N/2)*cell,dx=tx-monster.position.x,dz=tz-monster.position.z,d=Math.hypot(dx,dz);if(d<.25){monsterPath.shift();return}monster.position.x+=dx/d*speed*dt;monster.position.z+=dz/d*speed*dt;monster.rotation.y=Math.atan2(-dx,-dz)}
function updateMap(){let c=$('mapCanvas').getContext('2d'),w=150;c.clearRect(0,0,w,w);c.fillStyle='#050505';c.fillRect(0,0,w,w);let [px,pz]=gridAt(player.position.x,player.position.z),scale=5;for(let z=Math.max(0,pz-14);z<Math.min(N,pz+15);z++)for(let x=Math.max(0,px-14);x<Math.min(N,px+15);x++)if(!maze[z][x].v){let dx=(x-px)*scale+w/2,dz=(z-pz)*scale+w/2;c.fillStyle='#161616';c.fillRect(dx,dz,scale,scale)}for(let o of orbs)if(o.visible&&o.position.distanceTo(player.position)<12){let [x,z]=gridAt(o.position.x,o.position.z);c.fillStyle='#16aaff';c.fillRect(w/2+(x-px)*scale-1,w/2+(z-pz)*scale-1,3,3)}c.fillStyle='#fff';c.fillRect(w/2-2,w/2-2,4,4);c.strokeStyle='#fff';c.beginPath();c.moveTo(w/2,w/2);c.lineTo(w/2+Math.sin(yaw)*9,w/2-Math.cos(yaw)*9);c.stroke()}
function update(dt){if(!running)return;let forward=(keys.KeyW||keys.ArrowUp?1:0)-(keys.KeyS||keys.ArrowDown?1:0)+move.y,side=(keys.KeyD||keys.ArrowRight?1:0)-(keys.KeyA||keys.ArrowLeft?1:0)+move.x;let len=Math.hypot(forward,side);if(len>1){forward/=len;side/=len}isRunning=!!(keys.ShiftLeft||keys.ShiftRight||touchRun);let speed=moveSpeed*(isRunning?2:1);let dx=(Math.sin(yaw)*forward+Math.cos(yaw)*side)*speed*dt,dz=(-Math.cos(yaw)*forward+Math.sin(yaw)*side)*speed*dt;moveEntity(player,dx,dz);camera.position.copy(player.position);camera.rotation.order='YXZ';camera.rotation.y=yaw;camera.rotation.x=pitch;const fl=camera.children.find(o=>o.isSpotLight);fl.intensity=mode==='steals'?7:0;fl.position.set(0,0,0);fl.target.position.set(0,0,-1);if(flashTimer>0){flashTimer-=dt;const l=new THREE.PointLight(0xffffff,mode==='steals'?8:12,13);l.position.copy(camera.position);scene.add(l);setTimeout(()=>scene.remove(l),80)}for(let o of orbs){if(o.visible){o.rotation.y+=dt*1.4;if(o.position.distanceTo(player.position)<.75){o.visible=false;orbTotal--;if(mode==='shutter')batteries=Math.min(10,batteries+1);$('orbCount').textContent=`BLUE ORBS: ${orbTotal}`;toast(`${orbTotal} BLUE ORBS LEFT`);if(orbTotal===0){running=false;$('hud').hidden=true;$('ending').hidden=false}}}}updateMonster(dt);let distance=monster.position.distanceTo(player.position);shake=state==='chase'?Math.max(0,(8-distance)/8)*.07:Math.max(0,(4-distance)/4)*.025;if(shake){camera.position.x+=((Math.random()-.5)*shake);camera.position.y+=(Math.random()-.5)*shake}if(toastTimer>0){toastTimer-=dt;if(toastTimer<=0)$('toast').textContent=''}$('battery').textContent=`BATTERY: ${batteries}`;updateMap()}
function loop(){requestAnimationFrame(loop);let dt=Math.min(clock.getDelta(),.05);update(dt);renderer.render(scene,camera)}loop();
$('menu').querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>start(b.dataset.mode)));$('quit').addEventListener('click',()=>{running=false;$('hud').hidden=true;$('menu').hidden=false});$('back').addEventListener('click',()=>{$('ending').hidden=true;$('menu').hidden=false});$('action').addEventListener('pointerdown',e=>{e.preventDefault();flash()});let touchRun=false;$('run').addEventListener('pointerdown',e=>{e.preventDefault();touchRun=true});$('run').addEventListener('pointerup',()=>touchRun=false);$('run').addEventListener('pointercancel',()=>touchRun=false);window.addEventListener('keydown',e=>{keys[e.code]=true;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault();if(e.code==='Space')flash()});window.addEventListener('keyup',e=>keys[e.code]=false);
let lookPointer=null,lastX=0,lastY=0;canvas.addEventListener('pointerdown',e=>{if(!running)return;lookPointer=e.pointerId;lastX=e.clientX;lastY=e.clientY;canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(lookPointer!==e.pointerId)return;let dx=e.clientX-lastX,dy=e.clientY-lastY;lastX=e.clientX;lastY=e.clientY;yaw-=dx*.006;pitch=Math.max(-1.2,Math.min(1.2,pitch-dy*.005))});canvas.addEventListener('pointerup',e=>{if(lookPointer===e.pointerId)lookPointer=null});canvas.addEventListener('pointercancel',()=>lookPointer=null);
const stick=$('stick'),nub=stick.querySelector('i');let stickId=null,stickRect;stick.addEventListener('pointerdown',e=>{stickId=e.pointerId;stick.setPointerCapture(e.pointerId);stickRect=stick.getBoundingClientRect();stickMove(e)});function stickMove(e){let cx=stickRect.left+stickRect.width/2,cy=stickRect.top+stickRect.height/2,dx=e.clientX-cx,dy=e.clientY-cy,r=36,d=Math.hypot(dx,dy);if(d>r){dx=dx/d*r;dy=dy/d*r}nub.style.transform=`translate(${dx}px,${dy}px)`;move.x=dx/r;move.y=-dy/r}stick.addEventListener('pointermove',e=>{if(e.pointerId===stickId)stickMove(e)});function resetStick(){stickId=null;move={x:0,y:0};nub.style.transform=''}stick.addEventListener('pointerup',resetStick);stick.addEventListener('pointercancel',resetStick);
